plugins:
  - jekyll-remote-theme

remote_theme: "mmistakes/so-simple-theme@3.2.0"

title: Peter Kun, PhD
description: Portfolio and things.

      
skin: "/assets/css/skins/dark.css"
locale: en-US
baseurl: # the subpath of your site, e.g. "/blog"
url: # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
logo: # path of site logo, e.g. "/images/logo.png"
date_format: "%B %-d, %Y"
read_time: # reading time estimates, e.g. true
words_per_minute: # 200

google_fonts:
  - name: "Inter"
    weights: "300,400,700"
  - name: "Lora"
    weights: "100,400,400i,500,500i"
# google_analytics: # Google Analytics id, e.g. "UA-NNNNNNNN-N"
# disqus:
#   shortname: # Disqus shortname, e.g. "my_disqus_shortname"
twitter:
  username: # site's Twitter username, e.g. "mmistakes"

# Liquid
liquid:
  error_mode: strict

# Build settings
permalink: /:categories/:title/
markdown: kramdown
feed:
  path: atom.xml

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  
collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/

# Front Matter Defaults
defaults:
  # Post defaults
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post
      comments: false
      share: false

  # Portfolio defaults
  - scope:
      path: "_portfolio"
      type: portfolio
    values:
      layout: post
      comments: false
      share: false

# Site Author
author:
  name:
  picture:
  email:
  twitter:
  links:
    - title:
      url:
      icon:

# Footer Links
footer_links:
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square